services:
  nginx:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/share/nginx/html
    restart: always

  todo-app:
    build: services/todo
    tty: true
    ports:
      - "4001:4001"
    volumes:
      - ./services/todo:/app
